# Generated by Django 2.1 on 2018-08-22 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180820_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('taskTime', models.DateTimeField(blank=True, null=True, verbose_name='Task Time')),
                ('hours', models.TimeField(blank=True, null=True)),
                ('minutes', models.TimeField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
